---
title: "Simple document"
output: github_document
---

This file is for doing data import 

```{r}
library(tidyverse)
library(readxl)
library(haven)
```

Import our first dataset.

```{r}
# always use relative paths

litters_df =
  read_csv(file = "data/FAS_litters.csv", 
           na = c("", "NA", ".")
  )

# data file uses both NA and . for missing values - we will look at this later

# cleaning out spaces from column names
litters_df = janitor::clean_names(litters_df)
```

Importing second dataset.
```{r}
pups_df = 
    read_csv("data/FAS_pups.csv",
             na = c("", "NA", "."),
             skip = 3
    )

pups_df = janitor::clean_names(pups_df)
```

## Look at the data
```{r}
head(litters_df, 15)
tail(pups_df, 5)
```

Skimming??
```{r}
skimr::skim(pups_df)
```

## Oh excel...
```{r}
mlb_df = read_excel("data/mlb11.xlsx")
```

Look at the data!
```{r}
mlb_df
```

Load some FOTR words from LOTR.

```{r}
fotr_df = 
  read_excel("data/LotR_Words.xlsx",
           range = "B3:D6"
  )
fotr_df
```

What about Two Towers?
```{r}
tt_df = 
  read_excel("data/LotR_Words.xlsx",
           range = "F3:H6"
  )
tt_df
```

## Import SAS

Read in the PULSE dataset.

```{r}
pulse_df = 
  read_sas("data/public_pulse_data.sas7bdat")

pulse_df = janitor::clean_names(pulse_df)
```





