---
title: "02_data_manipulation"
output: html_document
date: "2026-09-24"
---

```{r}
library(tidyverse)
```

```{r}
litters_df =
  read_csv(file = "data/FAS_litters.csv", 
           na = c("", "NA", ".")
  )
litters_df = janitor::clean_names(litters_df)

pups_df = 
    read_csv("data/FAS_pups.csv",
             na = c("", "NA", "."),
             skip = 3
    )
pups_df = janitor::clean_names(pups_df)
```

```{r}
select(litters_df, group, litter_number)

select(litters_df, group:gd_of_birth)

select(litters_df, -group)

select(litters_df, starts_with("gd"))

select(litters_df, starts_with("gd"), group)

select(litters_df, GROUP = group, everything())

select(litters_df, - starts_with("gd"))
```

a couple of alternatives
```{r}
rename(litters_df, GROUP = group)

relocate(litters_df, litter_number, gd0_weight)
#putting columns in a new order
```

in the pups dataset, select litter number, sex, and PD ears
```{r}
select(pups_df, litter_number, sex, pd_ears)
```

## 'filter' some rows
```{r}
filter(litters_df, gd_of_birth = 19)

filter(litters_df, pups_born_alive <= 5)

filter(litters_df, pups_born_alive != 6)

filter(litters_df, group %in% c("Con7", "Con8", pups_born_alive <7))

drop_na(litters_df, gd0_weight)
```


in the pups datsaset, keep only rows wehre PD walk is less than 11 and sex is 2
```{r}
filter(pups_df, pd_walk < 11, sex == 2)
```








