---
title: "Tidy Data"
output: github_document
date: "2026-09-29"
---
```{r}
library(tidyverse)
```

## lets tidy something
```{r}
pulse_df = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") |> 
  janitor::clean_names()
```

```{r}
pulse_tidy_df = 
  pulse_df |> 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    values_to = "bdi_score_"
  ) |> 
  mutate(
    visit = replace(visit, visit == "bl","00m")
  )
```

Practice!
Import litters data, keep columns litter number and GD weights, and tidy
```{r}
litters_df = 
  read_csv("data/FAS_litters.csv", na = c(".","","NA")) |> 
  janitor::clean_names() |> 
  select(litter_number, gd0_weight, gd18_weight) |> 
  pivot_longer(
    gd0_weight:gd18_weight, 
    names_to = "gd",
    names_prefix = "gd",
    values_to = "weight"
  ) |> 
  mutate(
    gd = case_match(
      gd,
      "gd0_weight"~ 0, 
      "gd0_weight"~ 0,
    )
  )
```

## Deliberately untidy data
```{r}
analysis_df = 
  tibble(
    groups = c("treatment", "treatment", "placebo", "placebo"),
    time = c("pre","post","pre","post"),
    mean_outcome = c(4, 8, 3.5, 4.6)
  )
```

Lets untidy this dataset for human readability
```{r}
analysis_df |> 
  pivot_wider(
    names_from = time,
    values_from = mean_outcome
  ) |> 
  knitr::kable()
```

## bind some rows 

first, import each LOTR movie table
```{r}
fellowship_df = 
  readxl::read_excel("data/LotR_Words.xlsx", range = "B3:D6") |> 
  mutate(movie = "fellowship")

two_tower_df = 
  readxl::read_excel("data/LotR_Words.xlsx", range = "F3:H6") |> 
  mutate(movie = "two towers")

return_df = 
  readxl::read_excel("data/LotR_Words.xlsx", range = "J3:L6") |> 
  mutate(movie = "return of the king")
```

Next, put all of these together and tidy
```{r}
lotr_df = 
  bind_rows(fellowship_df, two_tower_df, return_df) |> 
  janitor::clean_names() |> 
  relocate(movie) |> 
  pivot_longer(
    female:male,
    names_to = "gender",
    values_to = "words"
  )
```

```{r}
pups_df = 
  read_csv(
    "data/FAS_pups.csv",
    skip = 3,
    na = c(".","","NA")) |> 
      janitor::clean_names() |> 
  mutate(
    sex = case_match(
      sex,
      1 ~ "male",
      2 ~ "female"
    )
  )
# sex is 1 male and 2 female in data

litters_df = 
  read_csv(
    "data/FAS_litters.csv",
    na = c(".","","NA")) |> 
  janitor::clean_names() |> 
  relocate(litter_number) |> 
  separate(group, into = c("dose","day_of_tx"), 3) |> 
  mutate(
    dose = str_to_lower(dose),
    day_of_tx = as.numeric(day_of_tx),
    gd_weight_gain = gd18_weight - gd0_weight
  )

fas_df = 
  left_join(pups_df, litters_df, by = "litter_number")
```








